name: EzProfile
version: '1.0'
main: org.sirox.ezprofile.EzProfile
api-version: '1.21'

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    HMCCosmetics:
      load: BEFORE
      required: false